#!/bin/zsh

export LC_ALL="en_US.UTF-8"

# ----- oh-my-zsh -----
export ZSH=$HOME/.oh-my-zsh
export ENV_NAME="$(cat ~/.shell-setup/.env)"

ZSH_THEME="custom-robbyrussell"
DISABLE_AUTO_UPDATE="true"

plugins=(git z zsh-syntax-highlighting)

source /etc/profile
source $ZSH/oh-my-zsh.sh

# aliases
alias k="kubectl"
alias code="code -r"
alias watch="watch -c "

export CLICOLOR=1

# ----- homebrew -----
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha

# ----- golang -----
export GOPATH=$HOME/go
export CGO_CFLAGS_ALLOW="-fno-builtin-memcmp"
export CGO_CXXFLAGS_ALLOW="-fno-builtin-memcmp|-lpthread"
export PATH="$PATH:$GOROOT/bin"

# ----- grep -----
if [ -f /usr/local/Cellar/grep/3.1/bin/grep ]; then
  export PATH="/usr/local/Cellar/grep/3.1/bin/:$PATH"
  alias grep='ggrep  --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
fi

export PATH="$HOME/bin:$GOPATH/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:$PATH"


# ----- kuberenetes -----
if ! [ -x "$(command -v kubectl)" ]; then
    source <(kubectl completion zsh)
    
fi
if [ -f /usr/local/opt/kube-ps1/share/kube-ps1.sh ]; then
    source /usr/local/opt/kube-ps1/share/kube-ps1.sh
    PROMPT='$(kube_ps1)'$PROMPT
    kubeoff
fi
export KUBE_EDITOR="vim"

# ----- mac os key bindings -----
bindkey "^[[1;9D" backward-word
bindkey "^[[1;9C" forward-word
bindkey "^[[1;10D" beginning-of-line
bindkey "^[[1;10C" end-of-line
bindkey "^[[1;e~" backward-delete-word

# ----- node js & yarn ----- 
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

# ----- google cloud sdk ----- 
if [ -f "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ]; then
    source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
fi
if [ -f "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ]; then 
    source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
fi

# ----- pyenv -----
if [ x "$(command -v pyenv)" ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
fi
