#!/bin/zsh

export LC_ALL="en_US.UTF-8"

export ZSH=$HOME/.oh-my-zsh
export ENV_NAME="$(cat ~/.shell-setup/.env)"

ZSH_THEME="custom-muse"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"

plugins=(git z zsh-syntax-highlighting)

source /etc/profile
source $ZSH/oh-my-zsh.sh
